#! /bin/sh

sxhkd &
compton --config $HOME/.config/compton.conf -b &
nitrogen --restore &
xsetroot -cursor_name left_ptr

bspc monitor -d term web chat code music VI VII VIII

bspc config border_width         1
bspc config window_gap          10
bspc config focused_border_color \#285577
bspc config normal_border_color \#5e5e5e
bspc config -d ^2 window_gap    0
bspc config -d ^2 border_width  0

bspc config focus_follows_pointer true
bspc config top_padding 19
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle	 true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium-browser desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Firefox desktop='^2' follow=on

polybar top &
urxvtd -q -o -f &
